name: 'Build - Linux'
on:
  push:
    branches: [ 'main' ]
    paths:
      - 'abyss/**'
      - 'tests/**'
      - '.github/workflows/build-linux.yml'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'abyss/**'
      - 'tests/**'
      - '.github/workflows/build-linux.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: '${{ matrix.os.id }} (${{ matrix.compiler }}, ${{ matrix.cpp_std }})'
    runs-on: '${{ matrix.os.id }}'
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
          - { id: ubuntu-22.04, name: jammy }
          - { id: ubuntu-24.04, name: noble }
        compiler:
          - 'gcc-12'
          - 'gcc-13'
          - 'clang-17'
          - 'clang-18'
        cpp_std:
          - 'c++20'
          - 'c++23'
        include:
          - os: { id: ubuntu-24.04, name: noble }
            compiler: 'gcc-14'
            cpp_std: 'c++20'
          - os: { id: ubuntu-24.04, name: noble }
            compiler: 'gcc-14'
            cpp_std: 'c++23'
    steps:
      - name: 'Setup Runtime Environment'
        shell: bash
        env:
          WORKSPACE: '${{ github.workspace }}'
        run: |
          echo "$HOME/.local/bin:$PATH" > $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV
      - name: 'Setup GCC'
        if: startsWith(matrix.compiler, 'gcc')
        shell: bash
        run: |
          CXX=${CC/#gcc/g++}
          sudo apt-add-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install $CC $CXX
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
          echo "GCOV=${CC/#gcc/gcov}" >> $GITHUB_ENV
        env:
          CC: '${{ matrix.compiler }}'
      - name: 'Setup Clang'
        if: startsWith(matrix.compiler, 'clang')
        shell: bash
        run: |
          wget https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo apt-key add llvm-snapshot.gpg.key
          rm llvm-snapshot.gpg.key
          sudo apt-add-repository "deb https://apt.llvm.org/${{ matrix.os.name }}/ llvm-toolchain-${{ matrix.os.name }}${CC/#clang/} main"
          sudo apt-get update
          sudo apt-get install $CC
          CXX=${CC/#clang/clang++}
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
          echo "GCOV=${CC/#gcc/gcov}" >> $GITHUB_ENV
          echo "GCOV=/usr/lib/${CC/#clang/llvm}/bin/llvm-cov gcov" >> $GITHUB_ENV
        env:
          CC: '${{ matrix.compiler }}'
      - name: 'Checkout Source'
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: true
      - name: 'Setup build tools'
        shell: bash
        run: |
          python3 -m pip install --user meson ninja
        working-directory: '${{ runner.temp }}'
      - name: 'Tool Versions'
        shell: bash
        run: |
          $CC --version
          $CXX --version
          $GCOV --version
          meson --version
          ninja --version
      - name: 'Configure'
        run: meson build --prefix=$HOME/.local -Dcpp_std=${{ matrix.cpp_std }}
      - name: 'Build'
        run: ninja -C build
      - name: 'Test'
        run: ninja -C build test
